#server:
#  port: 8882
#
#spring:
#  application:
#    name: api-gateway
#  zipkin:
#    base-url: http://192.168.200.129:9411/ #zipkin地址
#    discovery-client-enabled: false  #不用开启服务发现
#  sleuth:
#    sampler:
#      probability: 1.0 #采样百分比
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.200.129:8848
#    gateway:
#      routes: #数组形式
#      - id: order-service  #路由唯一标识
#        #uri: http://127.0.0.1:8000  #想要转发到的地址
#        uri: lb://xdclass-order-service
#        order: 1 #优先级，数字越小优先级越高
#        predicates: #断言 配置哪个路径才转发
#        - Path=/order-server/**
#        filters: #过滤器，请求在传递过程中通过过滤器修改
#        - StripPrefix=1  #去掉第一层前缀
#      discovery:
#        locator:
#          enable: true #网关拉取nacos服务