#server:
#  port: 9003
#
#spring:
#  application:
#    name: xdclass-video-service
#  zipkin:
#    base-url: http://192.168.200.129:9411 #zipkin地址
#    discovery-client-enabled: false  #不用开启服务发现
#  sleuth:
#    sampler:
#      probability: 1.0 #采样百分比
#
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.200.129:3306/cloud_video?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: Sk123123/
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.200.129:8848
#    sentinel:
#      transport:
#        dashboard: 192.168.200.129:8080
#        port: 9998
#
## 控制台输出sql、下划线转驼峰
#mybatis:
#  configuration:
#   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#   map-underscore-to-camel-case: true